---
blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/dashpresshq/dashpress/discussions/new
    about: Share your ideas on how to make DashPress better.
  - name: DashPress Community Support
    url: https://discord.gg/aV6DxwXhzN
    about: Please ask and answer questions here.